name: Zkevm test harness build

on:
  push:
    branches: ["v1.4.0", "akash-dev-1-4"]

jobs:
  boojum-build-test:
    runs-on: [ self-hosted, ci-runner ]

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"
          token: ${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}

      - name: Setup rustup
        run: |
          wget -q -O - https://sh.rustup.rs | bash -s -- -y
          echo "${HOME}/.cargo/bin" >> "${GITHUB_PATH}"
          echo "CARGO_BUILD_JOBS=$(($(nproc) /2))" >> "${GITHUB_ENV}"
          echo "export PATH=\"$HOME/.cargo/bin:\$PATH\"" >> "${HOME}/.bash_profile"

      - name: setup rust
        run: |
          rustup set profile minimal
          rustup toolchain install nightly-2023-05-31
          rustup default nightly-2023-05-31

      - name: build
        run: |
          git config --global --add url."https://${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/
          git config --global --add url."https://${{ secrets.ZKSYNC_ADMIN_BOT_ORG_REPO_WRITE }}:x-oauth-basic@github.com/".insteadOf https://github.com/
          cargo +nightly-2023-05-31 build --release
          cargo +nightly-2023-05-31 test basic_test  --release -- --nocapture
